### ISSUE TITLE
validate compatibility with Serverless v4

### ISSUE THREAD

**Issue by ITProKyle** [rackspace/runway#2482]
Serverless v4 introduced the requirement for an access/license key. This can be provided by running `serverless login` (manual) or environment variable.

https://www.serverless.com/framework/docs/guides/upgrading-v4

Example output when auth/license key is missing (no TTY) (runway log message proceeding npm output to end of runway's execution):

```text
[runway] tmp:running npm ci...
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated appdirectory@0.1.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.

added 157 packages, and audited 158 packages in 1s

21 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

(node:105121) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

✖ Error: You must sign in or use a license key with Serverless Framework V.4 and later versions. Please use "serverless login".
    at Authentication.getAuthenticatedData (file:///home/kyle/.serverless/releases/4.4.0/package/dist/sf-core.js:647:10535)
    at async Authentication.resolverAuthenticate (file:///home/kyle/.serverless/releases/4.4.0/package/dist/sf-core.js:649:20575)
    at async _Meta.authenticateAndResolve (file:///home/kyle/.serverless/releases/4.4.0/package/dist/sf-core.js:682:31179)
    at async route (file:///home/kyle/.serverless/releases/4.4.0/package/dist/sf-core.js:968:13931)
    at async Object.run2 [as run] (file:///home/kyle/.serverless/releases/4.4.0/package/dist/sf-core.js:968:14419)
    at async run3 (file:///home/kyle/.serverless/releases/4.4.0/package/dist/sf-core.js:968:15683)

For help, try the following:
  • Run the command again with the "--debug" option
  • Run "serverless support"
  • Review the docs: https://www.serverless.com/framework/docs/
```

Example sls output with a TTY

```text
? Serverless Framework V4 CLI is free for developers and organizations making less than $2 million annually, but requires an account or a license key.

Please login/register or enter your license key: … 
▸ Login/Register
  Get A License
  Enter A License Key
  Explain Licensing Basics
```

**Comment by ITProKyle** [comment]
Tested locally as this project does not have a license key that can be added. If/when a license key can be obtained or serverless run without a key, tests will be updated to v4.
